import type { ConditionDef } from '../types';

/**
 * Core PF2e conditions. Valued conditions that tick down at end of turn
 * (Frightened, Clumsy, etc.) reduce by 1; removed at 0.
 */
export const PF2E_CONDITIONS: ConditionDef[] = [
  { id: 'blinded', name: 'Blinded', valued: false, ticksDown: null },
  { id: 'broken', name: 'Broken', valued: false, ticksDown: null },
  { id: 'clumsy', name: 'Clumsy', valued: true, ticksDown: 'turn-end' },
  { id: 'concealed', name: 'Concealed', valued: false, ticksDown: null },
  { id: 'confused', name: 'Confused', valued: false, ticksDown: null },
  { id: 'controlled', name: 'Controlled', valued: false, ticksDown: null },
  { id: 'dazzled', name: 'Dazzled', valued: false, ticksDown: null },
  { id: 'deafened', name: 'Deafened', valued: false, ticksDown: null },
  { id: 'doomed', name: 'Doomed', valued: true, ticksDown: null },
  { id: 'drained', name: 'Drained', valued: true, ticksDown: null },
  { id: 'dying', name: 'Dying', valued: true, ticksDown: null, description: 'Tracked on the combatant dying field' },
  { id: 'encumbered', name: 'Encumbered', valued: false, ticksDown: null },
  { id: 'enfeebled', name: 'Enfeebled', valued: true, ticksDown: 'turn-end' },
  { id: 'fascinated', name: 'Fascinated', valued: false, ticksDown: null },
  { id: 'fatigued', name: 'Fatigued', valued: false, ticksDown: null },
  { id: 'flat-footed', name: 'Off-Guard', valued: false, ticksDown: null },
  { id: 'fleeing', name: 'Fleeing', valued: false, ticksDown: null },
  { id: 'friendly', name: 'Friendly', valued: false, ticksDown: null },
  { id: 'frightened', name: 'Frightened', valued: true, ticksDown: 'turn-end' },
  { id: 'grabbed', name: 'Grabbed', valued: false, ticksDown: null },
  { id: 'helpful', name: 'Helpful', valued: false, ticksDown: null },
  { id: 'hidden', name: 'Hidden', valued: false, ticksDown: null },
  { id: 'hostile', name: 'Hostile', valued: false, ticksDown: null },
  { id: 'immobilized', name: 'Immobilized', valued: false, ticksDown: null },
  { id: 'indifferent', name: 'Indifferent', valued: false, ticksDown: null },
  { id: 'invisible', name: 'Invisible', valued: false, ticksDown: null },
  { id: 'observed', name: 'Observed', valued: false, ticksDown: null },
  { id: 'paralyzed', name: 'Paralyzed', valued: false, ticksDown: null },
  { id: 'persistent-damage', name: 'Persistent Damage', valued: false, ticksDown: null },
  { id: 'petrified', name: 'Petrified', valued: false, ticksDown: null },
  { id: 'prone', name: 'Prone', valued: false, ticksDown: null },
  { id: 'quickened', name: 'Quickened', valued: false, ticksDown: null },
  { id: 'restrained', name: 'Restrained', valued: false, ticksDown: null },
  { id: 'sickened', name: 'Sickened', valued: true, ticksDown: null, description: 'Reduce on successful Fort save' },
  { id: 'slowed', name: 'Slowed', valued: true, ticksDown: 'turn-end' },
  { id: 'stunned', name: 'Stunned', valued: true, ticksDown: 'turn-end' },
  { id: 'stupefied', name: 'Stupefied', valued: true, ticksDown: 'turn-end' },
  { id: 'unconscious', name: 'Unconscious', valued: false, ticksDown: null },
  { id: 'undetected', name: 'Undetected', valued: false, ticksDown: null },
  { id: 'unfriendly', name: 'Unfriendly', valued: false, ticksDown: null },
  { id: 'unnoticed', name: 'Unnoticed', valued: false, ticksDown: null },
  { id: 'wounded', name: 'Wounded', valued: true, ticksDown: null, description: 'Tracked on the combatant wounded field' },
];
